# Generated by Django 3.2.25 on 2024-05-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_userprofile_needs_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="needs_update",
        ),
    ]
