# Generated by Django 3.2.25 on 2024-04-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_mystery_box',
            field=models.BooleanField(default=False),
        ),
    ]
