# Generated by Django 3.2.25 on 2024-04-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_is_mystery_box"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_mystery_box",
        ),
    ]
