# Generated by Django 3.2.25 on 2024-04-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_is_mystery_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_mystery_box',
            field=models.BooleanField(default=False),
        ),
    ]
